name: Deploy new website

on:
  push:
    branches: ["jwolff_march_2026", "staging", "main"]
  workflow_dispatch:
    branches: ["jwolff_march_2026", "staging", "main"]

env:
  NODE_VERSION: "20.x"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::497503705704:role/GitHub-OIDC-Role
          aws-region: us-east-1

      - name: Deploy with SST
        env:
          VITE_APPINSIGHTS_CONNECTION_STRING: ${{ secrets.VITE_APPINSIGHTS_CONNECTION_STRING }}
        run: |
          if [[ "${{ github.ref_name }}" == "staging" ]]; then
            export STAGE="dev"
          fi
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            export STAGE="production"
          fi
          if [[ "${{ github.ref_name }}" == "jwolff_march_2026" ]]; then
            export STAGE="publish"
          fi
          npx sst deploy --stage $STAGE
